import '../Models/clinicModels.dart';

List<ClinicModel> mockClinics = [
  ClinicModel(
    id: 1,
    userName: 'drjohn',
    password: 'test123',
    address: '123 Main St',
    graduationDegree: 'MBBS',
    firstName: 'John',
    lastName: 'Doe',
    speciality: 'Cardiology',
    gender: 'Male',
    dob: '1980-01-01',
    clinicName: 'City Heart Clinic',
    phoneNo: '9876543210',
    clinicPhoneNo: '1234567890',
    role: 'doctor',
  ),
  ClinicModel(
    id: 2,
    userName: 'drsara',
    password: 'pass456',
    address: '456 Central Ave',
    graduationDegree: 'BDS',
    firstName: 'Sara',
    lastName: 'Singh',
    speciality: 'Dentistry',
    gender: 'Female',
    dob: '1985-05-20',
    clinicName: 'Smile Dental',
    phoneNo: '9988776655',
    clinicPhoneNo: '1122334455',
    role: 'doctor',
  ),
  ClinicModel(
    id: 3,
    userName: 'neha.gyne',
    password: 'gyne2025',
    address: '789 Elm Road',
    graduationDegree: 'MD',
    firstName: 'Neha',
    lastName: 'Verma',
    speciality: 'Gynecology',
    gender: 'Female',
    dob: '1990-03-15',
    clinicName: 'Women Care',
    phoneNo: '9101234567',
    clinicPhoneNo: '2233445566',
    role: 'doctor',
  ),
  ClinicModel(
    id: 4,
    userName: 'rahul.ortho',
    password: 'ortho321',
    address: '22 Lake View',
    graduationDegree: 'MS',
    firstName: 'Rahul',
    lastName: 'Kumar',
    speciality: 'Orthopedics',
    gender: 'Male',
    dob: '1976-09-09',
    clinicName: 'Bone & Joint Clinic',
    phoneNo: '9876677001',
    clinicPhoneNo: '7788990011',
    role: 'doctor',
  ),
  ClinicModel(
    id: 5,
    userName: 'dr.anil',
    password: 'skin999',
    address: '5 Green Park',
    graduationDegree: 'MD',
    firstName: 'Anil',
    lastName: 'Patil',
    speciality: 'Dermatology',
    gender: 'Male',
    dob: '1982-07-22',
    clinicName: 'Skin Solutions',
    phoneNo: '9988001122',
    clinicPhoneNo: '3344556677',
    role: 'doctor',
  ),
];
